name: Release Changelog Builder

on:
  push:
    tags:
      - 'v*.*.*'  # Ã–rneÄŸin, v1.0.0 gibi etiketlere tetiklenir

jobs:
  build_changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Depoyu Klonla
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: SÃ¼rÃ¼m NotlarÄ±nÄ± OluÅŸtur
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          configurationJson: |
            {
              "template": "# {{CHANGELOG}}\n\n<details>\n<summary>Uncategorized</summary>\n\n{{UNCATEGORIZED}}\n</details>",
              "categories": [
                {
                  "title": "## ğŸš€ Ã–zellikler",
                  "labels": ["feature"]
                },
                {
                  "title": "## ğŸ› DÃ¼zeltmeler",
                  "labels": ["fix"]
                },
                {
                  "title": "## ğŸ§ª Testler",
                  "labels": ["test"]
                },
                {
                  "title": "## ğŸ’¬ DiÄŸer",
                  "labels": ["other"]
                },
                {
                  "title": "## ğŸ“¦ BaÄŸÄ±mlÄ±lÄ±klar",
                  "labels": ["dependencies"]
                }
              ]
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: GitHub SÃ¼rÃ¼mÃ¼nÃ¼ OluÅŸtur
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          body: ${{ steps.build_changelog.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
